language: c
compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: osx
      osx_image: xcode8

before_install:
    - git config --local user.name "Travis CI"
    - git config --local user.email "travis@coldlogix.com"
    - git tag "$(date +'%Y%m%d-%H:%M:%S')-$(git log --format=%h -1)"
    - eval "${MATRIX_EVAL}"

notifications: # set notification options
  email:
    recipients:
      - travis@coldlogix.com

deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      file_glob: true
      file: lmeter*.tar.gz

branches:
  only:
    - master
    - lm212_coldlogix
    - ngst_coldlogix

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make && make package


